# notes:
# - python >= 3.7 required for datetime.fromisoformat

{% set name = "toasty" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toasty-{{ version }}.tar.gz
  sha256: 7dc880b5ece31eace5636fecd80634a3b44a1e329f8f7a6dd2bec05b896597a5

build:
  number: 0
  entry_points:
    - toasty=toasty.cli:entrypoint
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - pillow >=7.0
    - python
    - pyyaml >=5.0
    - tqdm >=4.0
    - wwt_data_formats >=0.2.0

test:
  imports:
    - toasty
  commands:
    - pip check
    - toasty --help
    - pytest --pyargs toasty
  requires:
    - astropy
    - healpy  # [not win]
    - openexr-python
    - pip
    - pytest

about:
  home: https://toasty.readthedocs.io/
  summary: Generate TOAST image tile pyramids from existing image data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
