# notes:
# - python >= 3.7 required for datetime.fromisoformat
# - we have chosen to make the following dependencies optional:
#   - astropy
#   - requests
# - the conda-forge deps analyzer reports cython as missing, but it's appropriately
#   marked as build-time-only

{% set name = "toasty" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/toasty-{{ version }}.tar.gz
  sha256: c52fa6634934b4e7223cc0cc7032b88a1928de6525334f2a7ec636bc2f11a8f5

build:
  number: 0
  entry_points:
    - toasty=toasty.cli:entrypoint
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - filelock >=3
    - {{ pin_compatible('numpy') }}
    - pillow >=7.0
    - python
    - pyyaml >=5.0
    - reproject >=0.8
    - shapely
    - tqdm >=4.0
    - wwt_data_formats >=0.9.1

test:
  imports:
    - toasty
  commands:
    - pip check
    - toasty --help
    - pytest --pyargs toasty
  requires:
    - astropy
    - healpy  # [not win]
    - openexr-python
    - pip
    - pytest

about:
  home: https://toasty.readthedocs.io/
  summary: Generate TOAST image tile pyramids from existing image data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
